//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMNOP_System01.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calidad_Detenido
    {
        public int Id { get; set; }
        public string Defecto { get; set; }
        public string Seguimiento { get; set; }
        public string Comentario { get; set; }
        public string Nombre_detenido { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Hora { get; set; }
    }
}
