//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMNOP_System01.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estatus01_CentroServicio
    {
        public int Id { get; set; }
        public Nullable<int> Maquila { get; set; }
        public string Estatus { get; set; }
    }
}
